# site settings
title: REA
subtitle: NewHomes Project & Listing
email: bsi@thoughtworks.com
description: Our team attach greate importance to Effetive delivery and continuous improvement.
baseurl: "/planet-for-share" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 陕西省西安市高新区天谷八路211号环普科技产业园E座
github: BestTeamInTheWrold

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
